"""
System 2 Intelligence Backend Server
- Runs on 127.0.0.1:8102
- Loopback-only, non-authoritative, and replaceable.
- Hosts local model integration (Ollama, LM Studio, llama.cpp).
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from .service import System2Service

# Initialize System 2 Service
system2_service = System2Service()

# FastAPI App for System 2
app = FastAPI(
    title="System 2 Intelligence",
    version="3.2.0",
    description="Local intelligence backend for Agentic-AI. Non-authoritative and loopback-only.",
)

# CORS: Allow frontend and System 1 to interact
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://127.0.0.1:5173", "http://localhost:5173", "http://127.0.0.1:8000"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# --- Models ---
class ModelConfig(BaseModel):
    """Configuration for a local model."""
    name: str = Field(..., description="Model name (e.g., 'llama-3.2:70b')")
    provider: str = Field(..., description="Provider (e.g., 'Ollama', 'LM Studio')")
    endpoint: str = Field(..., description="Endpoint URL (must be loopback)")
    enabled: bool = Field(default=True, description="Whether the model is enabled")
    priority: int = Field(default=1, ge=0, le=10, description="Priority (higher = preferred)")


class System2Proposal(BaseModel):
    """A proposal generated by System 2."""
    task_id: str = Field(..., description="Associated task ID")
    run_id: str = Field(..., description="Associated run ID")
    goal: str = Field(..., description="Task goal")
    plan: Dict[str, Any] = Field(..., description="Proposed plan (DAG)")
    confidence: float = Field(default=0.8, ge=0.0, le=1.0, description="Confidence score")
    reasoning: str = Field(default="", description="System 2 reasoning")


# --- Endpoints ---

@app.get("/api/system2/health")
def system2_health() -> Dict[str, Any]:
    """
    Check System 2 health.
    - Returns status, active model, and loopback enforcement.
    """
    return {
        "status": system2_service.get_status(),
        "service": "System 2 Intelligence",
        "version": "3.2.0",
        "active_model": system2_service.get_active_model(),
        "loopback_only": True,
        "authority": False,
        "network_scope": "loopback",
    }


@app.get("/api/system2/models")
def list_models() -> List[Dict[str, Any]]:
    """
    List all local models.
    """
    return system2_service.list_models()


@app.get("/api/system2/models/{model_name}")
def get_model(model_name: str) -> Dict[str, Any]:
    """
    Get details of a specific model.
    """
    model = system2_service.get_model(model_name)
    if not model:
        raise HTTPException(status_code=404, detail="Model not found")
    return model


@app.post("/api/system2/models/{model_name}/activate")
def activate_model(model_name: str) -> Dict[str, Any]:
    """
    Activate a local model.
    """
    success = system2_service.activate_model(model_name)
    if not success:
        raise HTTPException(status_code=404, detail="Model not found")
    return {"status": "activated", "model": model_name}


@app.post("/api/system2/models/{model_name}/deactivate")
def deactivate_model(model_name: str) -> Dict[str, Any]:
    """
    Deactivate a local model.
    """
    success = system2_service.deactivate_model(model_name)
    if not success:
        raise HTTPException(status_code=404, detail="Model not found")
    return {"status": "deactivated", "model": model_name}


@app.post("/api/system2/models/discover")
def discover_models() -> Dict[str, Any]:
    """
    Discover local models (Ollama, LM Studio, llama.cpp).
    """
    discovered = system2_service.discover_models()
    return {
        "discovered": len(discovered),
        "models": discovered,
    }


@app.post("/api/system2/proposal")
def generate_proposal(proposal: System2Proposal) -> Dict[str, Any]:
    """
    Generate a proposal for a task (called by Agent Kernel).
    - System 2 can only propose; it cannot authorize or execute.
    """
    # Validate loopback endpoint
    if not system2_service.is_loopback(proposal.endpoint):
        raise HTTPException(
            status_code=400,
            detail="System 2 must use loopback endpoints only (127.0.0.1, localhost, ::1)",
        )

    # Generate proposal (placeholder: return input for now)
    proposal_dict = proposal.model_dump()
    proposal_dict["authority"] = False  # Explicitly mark as non-authoritative
    return {
        "proposal_id": system2_service.log_proposal(proposal_dict),
        "proposal": proposal_dict,
        "message": "Proposal generated. Awaiting System 1 validation.",
    }


@app.get("/api/system2/status")
def system2_status() -> Dict[str, Any]:
    """
    Get System 2 status (CPU, memory, latency).
    """
    return {
        "status": system2_service.get_status(),
        "cpu_usage": system2_service.get_cpu_usage(),
        "memory_usage": system2_service.get_memory_usage(),
        "latency": system2_service.get_latency(),
    }


@app.post("/api/system2/start")
def start_system2() -> Dict[str, Any]:
    """
    Start System 2 (idempotent).
    """
    system2_service.start()
    return {"status": "started", "message": "System 2 is running."}


@app.post("/api/system2/stop")
def stop_system2() -> Dict[str, Any]:
    """
    Stop System 2.
    """
    system2_service.stop()
    return {"status": "stopped", "message": "System 2 is stopped."}


@app.post("/api/system2/restart")
def restart_system2() -> Dict[str, Any]:
    """
    Restart System 2.
    """
    system2_service.restart()
    return {"status": "restarted", "message": "System 2 is restarted."}


# --- Run Server ---
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8102, log_level="info")
