import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API='http://localhost:8000/api';
type Brain=any;type Task=any;type Run=any;
function App(){const[goal,setGoal]=useState('');const[tasks,setTasks]=useState<Task[]>([]);const[runs,setRuns]=useState<Run[]>([]);const[brain,setBrain]=useState<Brain|null>(null);const[policy,setPolicy]=useState<Brain|null>(null);const[discover,setDiscover]=useState<any[]>([]);const[tab,setTab]=useState('Dashboard');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[model,setModel]=useState('');const[localUrl,setLocalUrl]=useState('http://127.0.0.1:1234');const[localName,setLocalName]=useState('local-model');
const json=async(url:string,opt?:RequestInit)=>{const r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text());return r.json()};const load=async()=>{try{const[x,y,z]=await Promise.all([json(`${API}/brain/status`),json(`${API}/tasks`),json(`${API}/agent/runs`)]);setBrain(x);setTasks(y);setRuns(z.runs||[]);setPolicy(x.system1_policy);setModel(x.runtime?.active_system2||'')}catch{setMsg('Backend offline — start FastAPI on port 8000.')}};useEffect(()=>{load()},[]);
const runAgent=async()=>{if(!goal.trim())return;setBusy(true);try{const x=await json(`${API}/agent/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal,autonomy:1,max_iterations:5,max_retries:2,confidence_threshold:.7})});setGoal('');setMsg(x.run.status==='completed'?'Agent completed and verified.':`Agent finished: ${x.run.status}`);await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
const discoverModels=async()=>{try{const x=await json(`${API}/brain/system2/discover`);setDiscover(x.models||x||[]);setMsg('Local model discovery completed.')}catch(e:any){setMsg(e.message)}};
const register=async()=>{try{await json(`${API}/brain/system2/local`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model_id:localName,base_url:localUrl,model_name:localName,provider:'local-openai-compatible'})});setMsg('Local System 2 model registered.');await load()}catch(e:any){setMsg(e.message)}};
const activate=async(id:string)=>{try{await json(`${API}/brain/models/active`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({model_id:id})});setModel(id);setMsg(`Active System 2: ${id}`);await load()}catch(e:any){setMsg(e.message)}};
const savePolicy=async(mode:string,conf:number,reviews:number)=>{try{const x=await json(`${API}/brain/system1/policy`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,minimum_confidence:conf,minimum_reviews:reviews})});setPolicy(x);setMsg('System 1 Council policy saved.')}catch(e:any){setMsg(e.message)}};
const nav=['Dashboard','Agent','System 1 Council','System 2 Models','Tasks','Memory','Evaluations','Tools','Logs','Settings'];return <div className="app"><aside><div className="brand">◈ Agentic<span>-AI</span></div>{nav.map(x=><button className={tab===x?'nav active':'nav'} onClick={()=>setTab(x)} key={x}>{x}</button>)}<div className="health"><i/> System 1 authoritative</div></aside><main><header><div><p className="eyebrow">GUARDED AGENT KERNEL • V2.5</p><h1>{tab}</h1></div><div className="pill">{brain?.runtime?.system2_network_policy||'LOCAL ONLY'}</div></header>{msg&&<div className="notice">{msg}</div>}
{tab==='Dashboard'&&<><section className="hero"><h2>Agentic AI Control Center</h2><p>System 1 governs. System 2 proposes. Every action passes permission, execution, verification and evaluation.</p><div className="composer"><textarea value={goal}onChange={e=>setGoal(e.target.value)}placeholder="Describe a goal for the agent…"/><button onClick={runAgent}disabled={busy}>{busy?'Running…':'Run Agent →'}</button></div></section><section className="grid"><div className="card"><label>AGENT RUNS</label><strong>{runs.length}</strong></div><div className="card"><label>COMPLETED</label><strong>{runs.filter(x=>x.status==='completed').length}</strong></div><div className="card"><label>SYSTEM 1</label><strong>{brain?.system1?.filter((x:any)=>x.configured).length||0} ready</strong></div><div className="card"><label>SYSTEM 2</label><strong>{brain?.system2?.length||0} local</strong></div></section><section className="panel"><div className="panelhead"><h3>Runtime Boundary</h3><button className="ghost"onClick={load}>Refresh</button></div><div className="steps"><div className="step"><span className="num">S1</span><div><b>System 1: authoritative control plane</b><small>Provider council, permissions, risk decisions and escalation.</small></div></div><div className="step"><span className="num">S2</span><div><b>System 2: {model||'local-deterministic-v2.2'}</b><small>Local-only reasoning. Remote endpoints are prohibited.</small></div></div></div></section></>}
{tab==='System 1 Council'&&<section className="panel"><div className="panelhead"><h3>AI Council</h3><button className="ghost"onClick={load}>Refresh</button></div><div className="grid">{(brain?.system1||[]).map((p:any)=><div className="card provider"key={p.model_id}><label>{p.provider||'builtin'}</label><strong>{p.model_id}</strong><small>{p.configured?'● Configured':'○ Not configured'}</small></div>)}</div><div className="settings"><label>Decision policy</label><select value={policy?.mode||'consensus'}onChange={e=>setPolicy({...policy,mode:e.target.value})}><option>any</option><option>all</option><option>consensus</option></select><label>Minimum confidence: {Math.round((policy?.minimum_confidence??.5)*100)}%</label><input type="range"min="0"max="1"step=".05"value={policy?.minimum_confidence??.5}onChange={e=>setPolicy({...policy,minimum_confidence:Number(e.target.value)})}/><label>Minimum reviews</label><input type="number"min="1"max="20"value={policy?.minimum_reviews??1}onChange={e=>setPolicy({...policy,minimum_reviews:Number(e.target.value)})}/><button onClick={()=>savePolicy(policy.mode,policy.minimum_confidence,policy.minimum_reviews)}>Save Council Policy</button></div></section>}
{tab==='System 2 Models'&&<><section className="panel"><div className="panelhead"><h3>Local Model Manager</h3><button className="ghost"onClick={discoverModels}>Discover Local Servers</button></div><div className="grid">{(brain?.system2||[]).map((m:any)=><div className="card provider"key={m.model_id}><label>SYSTEM 2</label><strong>{m.model_id}</strong><small>{m.active?'● ACTIVE':'Local / available'}</small><button className="ghost"onClick={()=>activate(m.model_id)}>Activate</button></div>)}</div></section><section className="panel"><h3>Register Local OpenAI-Compatible Server</h3><div className="formrow"><input value={localName}onChange={e=>setLocalName(e.target.value)}placeholder="Model ID"/><input value={localUrl}onChange={e=>setLocalUrl(e.target.value)}placeholder="http://127.0.0.1:1234"/><button onClick={register}>Register</button></div><div className="discovery">{discover.map((x:any)=><div className="task"key={x.provider}><div><b>{x.provider}</b><small>{x.base_url} · {x.reachable?'reachable':'offline'} · {x.latency_ms}ms</small></div><span>{x.health}</span></div>)}</div></section></>}
{tab==='Agent'&&<section className="panel"><h3>Agent Runs</h3>{runs.length?runs.map(r=><div className="task"key={r.run_id}><div><b>{r.goal}</b><small>{r.phase} · iteration {r.iteration}/{r.max_iterations}</small></div><span>{r.status}</span></div>):<div className="empty">No runs yet.</div>}</section>}
{tab==='Tasks'&&<section className="panel"><h3>Task History</h3>{tasks.length?tasks.slice(0,20).map(t=><div className="task"key={t.id}><div><b>{t.goal}</b><small>{new Date(t.created_at).toLocaleString()}</small></div><span>{t.status}</span></div>):<div className="empty">No tasks yet.</div>}</section>}
{['Memory','Evaluations','Tools','Logs','Settings'].includes(tab)&&<section className="panel"><h3>{tab}</h3><p className="muted">Control surface ready. Existing backend APIs remain available; this V2.5 screen focuses on the Model Manager and System 1 Council.</p></section>}
</main></div>};createRoot(document.getElementById('root')!).render(<App/>);