import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Step={id:string;title:string;tool:string;status:string;risk:string;output?:unknown;error?:string;duration_ms?:number;attempts?:number};
type TraceEvent={type:string;at:string;step_id?:string;tool?:string;status?:string;error?:string;duration_ms?:number;output?:unknown};
type Task={id:string;goal:string;status:string;autonomy:number;created_at:string;steps:Step[];verification?:{passed:boolean;method:string};evaluation?:any;result?:string};
type AgentRun={run_id:string;task_id:string;goal:string;status:string;phase:string;iteration:number;max_iterations:number;confidence_threshold:number;memory_context:any[];decisions:any[];error?:string;result?:string;started_at:string;finished_at?:string};
const API='http://localhost:8000/api';

function App(){
 const [goal,setGoal]=useState(''); const [tasks,setTasks]=useState<Task[]>([]); const [runs,setRuns]=useState<AgentRun[]>([]); const [selected,setSelected]=useState<Task|null>(null); const [run,setRun]=useState<AgentRun|null>(null); const [trace,setTrace]=useState<TraceEvent[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const load=()=>Promise.all([fetch(`${API}/tasks`).then(r=>r.json()).then(setTasks),fetch(`${API}/agent/runs`).then(r=>r.json()).then(x=>setRuns(x.runs||[]))]).catch(()=>setMessage('Backend offline — start FastAPI on port 8000.'));
 const loadTrace=(taskId:string)=>fetch(`${API}/tasks/${taskId}/trace`).then(r=>r.json()).then(x=>setTrace(x.events||[])).catch(()=>setTrace([]));
 useEffect(()=>{load()},[]);
 const select=(t:Task)=>{setSelected(t);setRun(runs.find(x=>x.task_id===t.id)||null);loadTrace(t.id)};
 const createAgent=async()=>{if(!goal.trim())return;setBusy(true);setMessage('Agent: understanding → memory → reasoning → guarded execution…');try{const r=await fetch(`${API}/agent/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal,autonomy:1,max_iterations:5,max_retries:2,confidence_threshold:.7})});const x=await r.json();setGoal('');setSelected(x.task);setRun(x.run);await loadTrace(x.task.id);await load();setMessage(x.run.status==='completed'?'Agent completed and verified.':`Agent finished with status: ${x.run.status}.`)}catch{setMessage('Could not reach backend.')}finally{setBusy(false)}};
 const cancel=async()=>{if(!run)return;await fetch(`${API}/agent/${run.run_id}/cancel`,{method:'POST'});setMessage('Agent cancellation requested.');await load();if(selected)await loadTrace(selected.id)};
 const evaluate=async()=>{if(!selected)return;const r=await fetch(`${API}/tasks/${selected.id}/evaluate`,{method:'POST'});const evaluation=await r.json();setSelected({...selected,evaluation});await loadTrace(selected.id);await load()};
 return <div className="app"><aside><div className="brand">◈ Agentic<span>-AI</span></div><nav>{['Dashboard','Agent','Planner','Tasks','Tools','Memory','Skills','Evaluations','Models','Experiments','Logs','Settings'].map((x,i)=><div className={i===1?'active':''} key={x}>{x}</div>)}</nav><div className="health"><i/> System 1 control plane online</div></aside>
 <main><header><div><p className="eyebrow">GUARDED AGENT KERNEL • V2.0</p><h1>Agent Control Center</h1></div><div className="pill">SYSTEM 1 + SYSTEM 2</div></header>
 <section className="hero"><div><h2>Give the agent a goal</h2><p>Understand → Retrieve Memory → Reason → Plan → Dry Run → Permission → Execute → Observe → Verify → Evaluate → Learn.</p><div className="composer"><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Describe a goal for the local agent…"/><button onClick={createAgent} disabled={busy}>{busy?'Running…':'Run Agent →'}</button></div>{message&&<div className="notice">{message}</div>}</div></section>
 <section className="grid"><div className="card"><label>ACTIVE / RECENT RUNS</label><strong>{runs.length}</strong></div><div className="card"><label>COMPLETED</label><strong>{runs.filter(r=>r.status==='completed').length}</strong></div><div className="card"><label>ESCALATED</label><strong>{runs.filter(r=>r.status==='escalated').length}</strong></div><div className="card"><label>MODE</label><strong>Guarded</strong></div></section>
 {run&&<section className="panel"><div className="panelhead"><h3>Agent Run · {run.phase.replaceAll('_',' ')}</h3>{['running','cancel_requested'].includes(run.status)&&<button className="ghost" onClick={cancel}>Stop Agent</button>}</div><div className="goal">{run.goal}</div><div className="steps"><div className="step"><span className="num">AI</span><div><b>Run status: {run.status}</b><small>Phase: {run.phase} · Iteration {run.iteration}/{run.max_iterations} · Confidence target {Math.round(run.confidence_threshold*100)}%</small></div></div><div className="step"><span className="num">M</span><div><b>Memory context</b><small>{run.memory_context.length} ranked memories retrieved for this goal.</small>{run.memory_context.slice(0,4).map((m:any)=><code key={m.memory_id}>{m.kind}: {m.content}</code>)}</div></div>{run.decisions.slice(-3).map((d:any,i)=><div className="step" key={`${d.iteration}-${i}`}><span className="num">R</span><div><b>Reasoning decision · iteration {d.iteration}</b><small>{d.action} · confidence {d.confidence}</small><code>{d.reason}</code></div></div>)}</div>{run.error&&<div className="verification">⚠ {run.error}</div>}{run.result&&<div className="verification">✓ {run.result}</div>}</section>}
 {selected&&<section className="panel detail"><div className="panelhead"><h3>System 1 Execution Trace</h3><button className="ghost" onClick={()=>{setSelected(null);setRun(null)}}>Close</button></div><div className="goal">{selected.goal}</div><div className="steps">{selected.steps.map((s,i)=><div className="step" key={s.id}><span className="num">{i+1}</span><div><b>{s.title}</b><small>Tool: {s.tool} · Risk: {s.risk} · {s.status} {s.duration_ms!=null?`· ${s.duration_ms}ms`:''} {s.attempts?`· ${s.attempts} attempt(s)`:''}</small>{s.output!=null&&<code>{JSON.stringify(s.output)}</code>}{s.error&&<code>ERROR: {s.error}</code>}</div></div>)}</div><div className="actions"><button onClick={evaluate} disabled={busy}>Run Self-Evaluation</button></div>{selected.verification&&<div className="verification">✓ Verification: {selected.verification.passed?'PASSED':'FAILED'} · {selected.verification.method}</div>}{selected.evaluation&&<div className="evaluation"><b>Evaluation: {selected.evaluation.overall_status}</b><span>Score: {selected.evaluation.overall_score}</span></div>}
 <div className="trace"><div className="panelhead"><h4>Live Timeline</h4><button className="ghost" onClick={()=>loadTrace(selected.id)}>Refresh</button></div>{trace.length===0?<div className="empty">No events.</div>:trace.slice().reverse().map((e,i)=><div className="traceevent" key={`${e.at}-${i}`}><span className="dot"/><div><b>{e.type.replaceAll('_',' ')}</b><small>{new Date(e.at).toLocaleTimeString()} {e.step_id?`· ${e.step_id}`:''} {e.tool?`· ${e.tool}`:''}</small>{e.error&&<code>{e.error}</code>}{e.output&&<code>{JSON.stringify(e.output)}</code>}</div></div>)}</div></section>}
 <section className="panel"><div className="panelhead"><h3>Agent Run History</h3><button className="ghost" onClick={load}>Refresh</button></div>{runs.length===0?<div className="empty">No agent runs yet.</div>:runs.map(r=><button className="task" key={r.run_id} onClick={()=>{const t=tasks.find(x=>x.id===r.task_id);if(t)select(t)}}><div><b>{r.goal}</b><small>{new Date(r.started_at).toLocaleString()} · {r.phase} · iteration {r.iteration}</small></div><span className={r.status}>{r.status}</span></button>)}</section>
 <section className="panel"><div className="panelhead"><h3>Task History</h3></div>{tasks.length===0?<div className="empty">No tasks yet.</div>:tasks.slice(0,8).map(t=><button className="task" key={t.id} onClick={()=>select(t)}><div><b>{t.goal}</b><small>{new Date(t.created_at).toLocaleString()}</small></div><span className={t.status}>{t.status}</span></button>)}</section>
 </main></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
