import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './v31.css';

const API=(import.meta.env.VITE_API_URL||'http://127.0.0.1:8000/api').replace(/\/$/,'');
const terminal=['completed','failed','escalated','cancelled'];
async function api(path:string,opts:RequestInit={}){const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const text=await r.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{data={raw:text}}if(!r.ok)throw Error(data.detail||data.message||data.raw||`HTTP ${r.status}`);return data}

type Run={run_id:string,status:string,phase?:string,task_id?:string,[k:string]:any};
function App(){
 const [tab,setTab]=useState('Dashboard'); const [goal,setGoal]=useState('Return the current time and verify the output.'); const [run,setRun]=useState<Run|null>(null); const [trace,setTrace]=useState<any[]>([]); const [runtime,setRuntime]=useState<any>({}); const [backends,setBackends]=useState<any>({}); const [security,setSecurity]=useState<any>({}); const [health,setHealth]=useState<any>({}); const [audit,setAudit]=useState<any[]>([]); const [error,setError]=useState('');
 const nav=['Dashboard','Agent','System 1','System 2','Runtime','Tasks','Memory','Evaluations','Tools','Audit','Security','Settings'];
 const refresh=async()=>{try{const [rt,b,s,h,a]=await Promise.all([api('/runtime/status'),api('/backends/status'),api('/security/snapshot'),api('/security/system1-health'),api('/observability/audit?limit=50')]);setRuntime(rt);setBackends(b);setSecurity(s);setHealth(h);setAudit(a.events||[]);if(run){const x=await api('/agent/'+run.run_id+'/async-status');setRun(x.run);const t=await api('/agent/'+run.run_id+'/trace');setTrace(t.events||[])}setError('')}catch(e:any){setError(e.message)}};
 useEffect(()=>{refresh();const id=setInterval(refresh,1000);return()=>clearInterval(id)},[run?.run_id]);
 const launch=async()=>{try{const x=await api('/agent/run',{method:'POST',body:JSON.stringify({goal,autonomy:1,max_iterations:5,max_retries:2,confidence_threshold:.7})});setRun(x.run);setTab('Agent');setError('')}catch(e:any){setError(e.message)}};
 const control=async(action:string,body:any={})=>{try{await api('/backends/system2/'+action,{method:'POST',body:JSON.stringify(body)});await refresh()}catch(e:any){setError(e.message)}};
 const cancel=async()=>{if(run)try{await api('/agent/'+run.run_id+'/cancel',{method:'POST'});refresh()}catch(e:any){setError(e.message)}};
 const updateRuntime=async()=>{try{await api('/runtime/config',{method:'PUT',body:JSON.stringify({max_concurrency:Math.max(1,Number((document.getElementById('conc') as HTMLInputElement).value)),queue_limit:Math.max(1,Number((document.getElementById('queue') as HTMLInputElement).value))})});refresh()}catch(e:any){setError(e.message)}};
 const cards=useMemo(()=>[{k:'Runtime',v:runtime.active_jobs??0,s:'active jobs'},{k:'Queue',v:runtime.queued_jobs??0,s:'waiting'},{k:'System 1',v:health.healthy?'HEALTHY':'FAULT',s:`${health.checks||0} checks`},{k:'System 2',v:backends.system2?.state||'unknown',s:'lifecycle'}],[runtime,health,backends]);
 return <div className="shell"><aside><div className="logo">◈ <span>AGENTIC</span><small>AI CONTROL CORE · V3.1</small></div>{nav.map(n=><button className={tab===n?'nav active':'nav'} onClick={()=>setTab(n)}>{n}</button>)}<div className="authority"><b>SYSTEM 1</b><span>AUTHORITATIVE</span><i>● ALWAYS ON</i></div></aside><main><header><div><h1>{tab}</h1><p>Local-first agent runtime · System 1 governs execution</p></div><span className={health.healthy?'online':'offline'}>● {health.healthy?'ONLINE':'DEGRADED'}</span></header>{error&&<div className="error">{error}</div>}
 {tab==='Dashboard'&&<><div className="hero"><div><span className="eyebrow">AUTONOMOUS RUNTIME</span><h2>Observe. Reason. Govern. Execute.</h2><p>System 2 proposes locally. System 1 reviews and authorizes every execution path.</p></div><button className="primary" onClick={()=>setTab('Agent')}>OPEN AGENT →</button></div><div className="cards">{cards.map(c=><div className="card"><label>{c.k}</label><strong>{String(c.v)}</strong><small>{c.s}</small></div>)}</div><Panel title="Runtime topology"><pre>{JSON.stringify({system1:security.system1,system2:security.system2,execution_gate:security.execution_gate},null,2)}</pre></Panel></>}
 {tab==='Agent'&&<><Panel title="Launch asynchronous agent"><textarea value={goal} onChange={e=>setGoal(e.target.value)}/><div className="actions"><button className="primary" onClick={launch}>▶ START RUN</button>{run&&<button className="danger" onClick={cancel}>■ CANCEL</button>}</div></Panel>{run&&<><div className="cards"><div className="card"><label>STATUS</label><strong>{run.status}</strong></div><div className="card"><label>PHASE</label><strong>{run.phase||'—'}</strong></div><div className="card"><label>RUN ID</label><strong className="mono">{run.run_id}</strong></div></div><Panel title="Live event stream"><pre>{trace.map(x=>JSON.stringify(x)).join('\n')||'Waiting for events…'}</pre></Panel></>}</>}
 {tab==='System 1'&&<><Panel title="Authoritative System 1"><div className="cards"><div className="card"><label>HEALTH</label><strong>{health.healthy?'HEALTHY':'FAULT'}</strong></div><div className="card"><label>CHECKS</label><strong>{health.checks||0}</strong></div><div className="card"><label>FAILURES</label><strong>{health.failures||0}</strong></div></div><p>System 1 cannot be stopped by the frontend or System 2. It owns the execution authority and Council gate.</p><pre>{JSON.stringify(backends.system1,null,2)}</pre></Panel></>}
 {tab==='System 2'&&<Panel title="Local System 2 lifecycle"><pre>{JSON.stringify(backends.system2,null,2)}</pre><div className="actions"><button onClick={()=>control('start')}>START</button><button onClick={()=>control('stop')}>STOP</button><button onClick={()=>control('restart')}>RESTART</button><button onClick={()=>control('update')}>UPDATE</button></div><p>Loopback-only. No remote fallback. No System 1 authority.</p></Panel>}
 {tab==='Runtime'&&<Panel title="Execution runtime configuration"><div className="form"><label>Max concurrency<input id="conc" type="number" defaultValue={runtime.config?.max_concurrency||2}/></label><label>Queue limit<input id="queue" type="number" defaultValue={runtime.config?.queue_limit||20}/></label></div><button className="primary" onClick={updateRuntime}>SAVE RUNTIME</button><pre>{JSON.stringify(runtime,null,2)}</pre></Panel>}
 {tab==='Audit'&&<Panel title="Security / runtime audit"><pre>{JSON.stringify(audit,null,2)}</pre></Panel>}
 {tab==='Security'&&<Panel title="Security boundary"><pre>{JSON.stringify(security,null,2)}</pre></Panel>}
 {['Tasks','Memory','Evaluations','Tools','Settings'].includes(tab)&&<Panel title={tab}><p>Module connected to the existing Agentic-AI APIs. Live runtime and governance controls remain active.</p><pre>{JSON.stringify({runtime,backends},null,2)}</pre></Panel>}
 </main></div>}
function Panel(p:{title:string,children:any}){return <section className="panel"><h3>{p.title}</h3>{p.children}</section>}
createRoot(document.getElementById('root')!).render(<App/>);
